# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/bruin2/bruin_2_code/src/nodes/master/master_gui/resource/bruin2.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(889, 648)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_Title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Title.setGeometry(QtCore.QRect(270, 0, 169, 22))
        self.lbl_Title.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Courier 10 Pitch\";\n"
"font: 14pt \"Sans Serif\";")
        self.lbl_Title.setScaledContents(False)
        self.lbl_Title.setObjectName("lbl_Title")
        self.cB_StationNum = QtWidgets.QComboBox(self.centralwidget)
        self.cB_StationNum.setGeometry(QtCore.QRect(10, 10, 111, 22))
        self.cB_StationNum.setObjectName("cB_StationNum")
        self.cB_StationNum.addItem("")
        self.cB_StationNum.addItem("")
        self.cB_StationNum.addItem("")
        self.lbl_lattitude = QtWidgets.QLabel(self.centralwidget)
        self.lbl_lattitude.setGeometry(QtCore.QRect(130, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_lattitude.setFont(font)
        self.lbl_lattitude.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_lattitude.setObjectName("lbl_lattitude")
        self.lbl_longitude = QtWidgets.QLabel(self.centralwidget)
        self.lbl_longitude.setGeometry(QtCore.QRect(130, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_longitude.setFont(font)
        self.lbl_longitude.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_longitude.setObjectName("lbl_longitude")
        self.lbl_lattitudeNum = QtWidgets.QLabel(self.centralwidget)
        self.lbl_lattitudeNum.setGeometry(QtCore.QRect(200, 20, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_lattitudeNum.setFont(font)
        self.lbl_lattitudeNum.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_lattitudeNum.setObjectName("lbl_lattitudeNum")
        self.lbl_longitudeNum = QtWidgets.QLabel(self.centralwidget)
        self.lbl_longitudeNum.setGeometry(QtCore.QRect(200, 40, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_longitudeNum.setFont(font)
        self.lbl_longitudeNum.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_longitudeNum.setObjectName("lbl_longitudeNum")
        self.btn_debug = QtWidgets.QPushButton(self.centralwidget)
        self.btn_debug.setGeometry(QtCore.QRect(710, 10, 160, 27))
        self.btn_debug.setAutoFillBackground(False)
        self.btn_debug.setObjectName("btn_debug")
        self.lbl_map = QtWidgets.QLabel(self.centralwidget)
        self.lbl_map.setGeometry(QtCore.QRect(60, 100, 741, 471))
        self.lbl_map.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_map.setObjectName("lbl_map")
        self.lbl_black = QtWidgets.QLabel(self.centralwidget)
        self.lbl_black.setGeometry(QtCore.QRect(-50, -30, 1011, 681))
        self.lbl_black.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lbl_black.setText("")
        self.lbl_black.setScaledContents(True)
        self.lbl_black.setObjectName("lbl_black")
        self.lbl_currentState = QtWidgets.QLabel(self.centralwidget)
        self.lbl_currentState.setGeometry(QtCore.QRect(280, 20, 151, 21))
        self.lbl_currentState.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_currentState.setObjectName("lbl_currentState")
        self.lbl_StateType = QtWidgets.QLabel(self.centralwidget)
        self.lbl_StateType.setGeometry(QtCore.QRect(320, 40, 161, 17))
        self.lbl_StateType.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_StateType.setObjectName("lbl_StateType")
        self.lbl_longitudeNum2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_longitudeNum2.setGeometry(QtCore.QRect(570, 40, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_longitudeNum2.setFont(font)
        self.lbl_longitudeNum2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_longitudeNum2.setObjectName("lbl_longitudeNum2")
        self.lbl_lattitude2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_lattitude2.setGeometry(QtCore.QRect(500, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_lattitude2.setFont(font)
        self.lbl_lattitude2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_lattitude2.setObjectName("lbl_lattitude2")
        self.lbl_longitude2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_longitude2.setGeometry(QtCore.QRect(500, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_longitude2.setFont(font)
        self.lbl_longitude2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_longitude2.setObjectName("lbl_longitude2")
        self.lbl_lattitudeNum2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_lattitudeNum2.setGeometry(QtCore.QRect(570, 20, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_lattitudeNum2.setFont(font)
        self.lbl_lattitudeNum2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_lattitudeNum2.setObjectName("lbl_lattitudeNum2")
        self.lbl_Target = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Target.setGeometry(QtCore.QRect(500, 0, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_Target.setFont(font)
        self.lbl_Target.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_Target.setObjectName("lbl_Target")
        self.lbl_CurrentPos = QtWidgets.QLabel(self.centralwidget)
        self.lbl_CurrentPos.setGeometry(QtCore.QRect(130, 0, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_CurrentPos.setFont(font)
        self.lbl_CurrentPos.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_CurrentPos.setObjectName("lbl_CurrentPos")
        self.lbl_black.raise_()
        self.lbl_Title.raise_()
        self.cB_StationNum.raise_()
        self.lbl_lattitude.raise_()
        self.lbl_longitude.raise_()
        self.lbl_lattitudeNum.raise_()
        self.lbl_longitudeNum.raise_()
        self.btn_debug.raise_()
        self.lbl_map.raise_()
        self.lbl_currentState.raise_()
        self.lbl_StateType.raise_()
        self.lbl_longitudeNum2.raise_()
        self.lbl_lattitude2.raise_()
        self.lbl_longitude2.raise_()
        self.lbl_lattitudeNum2.raise_()
        self.lbl_Target.raise_()
        self.lbl_CurrentPos.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_Title.setText(_translate("MainWindow", "Bruin 2 Navigator"))
        self.cB_StationNum.setItemText(0, _translate("MainWindow", "None"))
        self.cB_StationNum.setItemText(1, _translate("MainWindow", "station1"))
        self.cB_StationNum.setItemText(2, _translate("MainWindow", "station2"))
        self.lbl_lattitude.setText(_translate("MainWindow", "Lattitude:"))
        self.lbl_longitude.setText(_translate("MainWindow", "Longitude:"))
        self.lbl_lattitudeNum.setText(_translate("MainWindow", "0"))
        self.lbl_longitudeNum.setText(_translate("MainWindow", "0"))
        self.btn_debug.setText(_translate("MainWindow", "Live Debugging Data"))
        self.lbl_map.setText(_translate("MainWindow", "Insert Photo Here"))
        self.lbl_currentState.setText(_translate("MainWindow", "Current Robot State:"))
        self.lbl_StateType.setText(_translate("MainWindow", "None"))
        self.lbl_longitudeNum2.setText(_translate("MainWindow", "0"))
        self.lbl_lattitude2.setText(_translate("MainWindow", "Lattitude:"))
        self.lbl_longitude2.setText(_translate("MainWindow", "Longitude:"))
        self.lbl_lattitudeNum2.setText(_translate("MainWindow", "0"))
        self.lbl_Target.setText(_translate("MainWindow", "Target:"))
        self.lbl_CurrentPos.setText(_translate("MainWindow", "Current Position:"))

