dist: xenial
sudo: false

before_install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 0xB01FA116
  - sudo apt update --fix-missing
  - sudo rm /var/lib/dpkg/lock
  - sudo apt install -y cmake ros-kinetic-desktop python-rosinstall libsdl2-dev python screen python-pip python-pyqt5 pyqt5-dev-tools gcc
  - pip install screeninfo
  - sudo rosdep init
  - rosdep update
  - source /opt/ros/kinetic/setup.bash

script:
  - cd src
  - sudo rm CMakeLists.txt
  - catkin_init_workspace
  - echo 'set(SDL2_LIBRARIES "-L${SDL2_LIBDIR}  -lSDL2")' | sudo tee -a /usr/lib/x86_64-linux-gnu/cmake/SDL2/sdl2-config.cmake
  - cd ..
  - catkin_make
  - cd src/nodes/master/state_machine/interface/test
  - make test
