dist: xenial
sudo: false

before_install:
  - sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 0xB01FA116
  - apt update
  - apt install -y cmake ros-kinetic-desktop-full python-rosinstall libsdl2-dev 
  - rosdep init
  - rosdep update
  - source /opt/ros/kinetic/setup.bash

script:
  - cd src
  - rm CMakeLists.txt
  - catkin_init_workspace
  - echo 'set(SDL2_LIBRARIES "-L${SDL2_LIBDIR}  -lSDL2")' | tee -a /usr/lib/x86_64-linux-gnu/cmake/SDL2/sdl2-config.cmake
  - cd ..
  - catkin_make
