# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/nathantheinventor/bruin_2_code/src/nodes/test/gui_test/resource/gui_test.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 101, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.relay01 = QtWidgets.QCheckBox(self.groupBox)
        self.relay01.setGeometry(QtCore.QRect(10, 40, 84, 19))
        self.relay01.setObjectName("relay01")
        self.relay02 = QtWidgets.QCheckBox(self.groupBox)
        self.relay02.setGeometry(QtCore.QRect(10, 60, 84, 19))
        self.relay02.setObjectName("relay02")
        self.relay03 = QtWidgets.QCheckBox(self.groupBox)
        self.relay03.setGeometry(QtCore.QRect(10, 80, 84, 19))
        self.relay03.setObjectName("relay03")
        self.relay04 = QtWidgets.QCheckBox(self.groupBox)
        self.relay04.setGeometry(QtCore.QRect(10, 100, 84, 19))
        self.relay04.setObjectName("relay04")
        self.relay05 = QtWidgets.QCheckBox(self.groupBox)
        self.relay05.setGeometry(QtCore.QRect(10, 120, 84, 19))
        self.relay05.setObjectName("relay05")
        self.relay06 = QtWidgets.QCheckBox(self.groupBox)
        self.relay06.setGeometry(QtCore.QRect(10, 140, 84, 19))
        self.relay06.setObjectName("relay06")
        self.relay07 = QtWidgets.QCheckBox(self.groupBox)
        self.relay07.setGeometry(QtCore.QRect(10, 160, 84, 19))
        self.relay07.setObjectName("relay07")
        self.relay08 = QtWidgets.QCheckBox(self.groupBox)
        self.relay08.setGeometry(QtCore.QRect(10, 180, 84, 19))
        self.relay08.setObjectName("relay08")
        self.relay09 = QtWidgets.QCheckBox(self.groupBox)
        self.relay09.setGeometry(QtCore.QRect(10, 200, 84, 19))
        self.relay09.setObjectName("relay09")
        self.relay10 = QtWidgets.QCheckBox(self.groupBox)
        self.relay10.setGeometry(QtCore.QRect(10, 220, 84, 19))
        self.relay10.setObjectName("relay10")
        self.relay11 = QtWidgets.QCheckBox(self.groupBox)
        self.relay11.setGeometry(QtCore.QRect(10, 240, 84, 19))
        self.relay11.setObjectName("relay11")
        self.relay12 = QtWidgets.QCheckBox(self.groupBox)
        self.relay12.setGeometry(QtCore.QRect(10, 260, 84, 19))
        self.relay12.setObjectName("relay12")
        self.relay13 = QtWidgets.QCheckBox(self.groupBox)
        self.relay13.setGeometry(QtCore.QRect(10, 280, 84, 19))
        self.relay13.setObjectName("relay13")
        self.relay14 = QtWidgets.QCheckBox(self.groupBox)
        self.relay14.setGeometry(QtCore.QRect(10, 300, 84, 19))
        self.relay14.setObjectName("relay14")
        self.relay15 = QtWidgets.QCheckBox(self.groupBox)
        self.relay15.setGeometry(QtCore.QRect(10, 320, 84, 19))
        self.relay15.setObjectName("relay15")
        self.relay00 = QtWidgets.QCheckBox(self.groupBox)
        self.relay00.setGeometry(QtCore.QRect(10, 20, 84, 19))
        self.relay00.setObjectName("relay00")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(120, 10, 201, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label.setObjectName("label")
        self.gps_lat = QtWidgets.QLabel(self.groupBox_2)
        self.gps_lat.setGeometry(QtCore.QRect(100, 20, 101, 16))
        self.gps_lat.setText("")
        self.gps_lat.setObjectName("gps_lat")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.label_2.setObjectName("label_2")
        self.gps_long = QtWidgets.QLabel(self.groupBox_2)
        self.gps_long.setGeometry(QtCore.QRect(100, 40, 101, 16))
        self.gps_long.setText("")
        self.gps_long.setObjectName("gps_long")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 57, 14))
        self.label_3.setObjectName("label_3")
        self.gps_alt = QtWidgets.QLabel(self.groupBox_2)
        self.gps_alt.setGeometry(QtCore.QRect(100, 60, 101, 16))
        self.gps_alt.setText("")
        self.gps_alt.setObjectName("gps_alt")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 57, 14))
        self.label_4.setObjectName("label_4")
        self.gps_vel = QtWidgets.QLabel(self.groupBox_2)
        self.gps_vel.setGeometry(QtCore.QRect(100, 80, 71, 16))
        self.gps_vel.setText("")
        self.gps_vel.setObjectName("gps_vel")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 57, 14))
        self.label_5.setObjectName("label_5")
        self.gps_hdop = QtWidgets.QLabel(self.groupBox_2)
        self.gps_hdop.setGeometry(QtCore.QRect(100, 100, 57, 14))
        self.gps_hdop.setText("")
        self.gps_hdop.setObjectName("gps_hdop")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 57, 14))
        self.label_6.setObjectName("label_6")
        self.gps_pdop = QtWidgets.QLabel(self.groupBox_2)
        self.gps_pdop.setGeometry(QtCore.QRect(100, 120, 57, 14))
        self.gps_pdop.setText("")
        self.gps_pdop.setObjectName("gps_pdop")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 140, 57, 14))
        self.label_7.setObjectName("label_7")
        self.gps_vdop = QtWidgets.QLabel(self.groupBox_2)
        self.gps_vdop.setGeometry(QtCore.QRect(100, 140, 57, 14))
        self.gps_vdop.setText("")
        self.gps_vdop.setObjectName("gps_vdop")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(120, 180, 201, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_8.setObjectName("label_8")
        self.compass_heading = QtWidgets.QLabel(self.groupBox_3)
        self.compass_heading.setGeometry(QtCore.QRect(100, 20, 61, 16))
        self.compass_heading.setText("")
        self.compass_heading.setObjectName("compass_heading")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.label_9.setObjectName("label_9")
        self.compass_pitch = QtWidgets.QLabel(self.groupBox_3)
        self.compass_pitch.setGeometry(QtCore.QRect(100, 40, 57, 14))
        self.compass_pitch.setText("")
        self.compass_pitch.setObjectName("compass_pitch")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 57, 14))
        self.label_10.setObjectName("label_10")
        self.compass_roll = QtWidgets.QLabel(self.groupBox_3)
        self.compass_roll.setGeometry(QtCore.QRect(100, 60, 57, 14))
        self.compass_roll.setText("")
        self.compass_roll.setObjectName("compass_roll")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.label_11.setObjectName("label_11")
        self.compass_temp = QtWidgets.QLabel(self.groupBox_3)
        self.compass_temp.setGeometry(QtCore.QRect(100, 80, 57, 14))
        self.compass_temp.setText("")
        self.compass_temp.setObjectName("compass_temp")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Relays"))
        self.relay01.setText(_translate("MainWindow", "Relay 1"))
        self.relay02.setText(_translate("MainWindow", "Relay 2"))
        self.relay03.setText(_translate("MainWindow", "Relay 3"))
        self.relay04.setText(_translate("MainWindow", "Relay 4"))
        self.relay05.setText(_translate("MainWindow", "Relay 5"))
        self.relay06.setText(_translate("MainWindow", "Relay 6"))
        self.relay07.setText(_translate("MainWindow", "Relay 7"))
        self.relay08.setText(_translate("MainWindow", "Relay 8"))
        self.relay09.setText(_translate("MainWindow", "Relay 9"))
        self.relay10.setText(_translate("MainWindow", "Relay 10"))
        self.relay11.setText(_translate("MainWindow", "Relay 11"))
        self.relay12.setText(_translate("MainWindow", "Relay 12"))
        self.relay13.setText(_translate("MainWindow", "Relay 13"))
        self.relay14.setText(_translate("MainWindow", "Relay 14"))
        self.relay15.setText(_translate("MainWindow", "Relay 15"))
        self.relay00.setText(_translate("MainWindow", "Relay 0"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GPS"))
        self.label.setText(_translate("MainWindow", "Latitude"))
        self.label_2.setText(_translate("MainWindow", "Longitude"))
        self.label_3.setText(_translate("MainWindow", "Altitude"))
        self.label_4.setText(_translate("MainWindow", "Velocity"))
        self.label_5.setText(_translate("MainWindow", "HDop"))
        self.label_6.setText(_translate("MainWindow", "PDop"))
        self.label_7.setText(_translate("MainWindow", "VDop"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Compass"))
        self.label_8.setText(_translate("MainWindow", "Heading"))
        self.label_9.setText(_translate("MainWindow", "Pitch"))
        self.label_10.setText(_translate("MainWindow", "Roll"))
        self.label_11.setText(_translate("MainWindow", "Temperature"))

